# Generated by Django 4.1.4 on 2023-01-07 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tasks_created', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('status', models.CharField(choices=[('TO_DO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='TO_DO', max_length=20)),
                ('place', models.CharField(max_length=50)),
                ('total_hours', models.PositiveIntegerField()),
                ('completed_hours', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_assigned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScholarshipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_year', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('age', models.PositiveSmallIntegerField()),
                ('financial_situation', models.CharField(choices=[('bad', 'Bad'), ('mid', 'Mid'), ('good', 'Good')], max_length=4)),
                ('parent_work', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('special_needs', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('tenant', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('volunteer', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
