# Generated by Django 3.2.7 on 2023-01-11 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20230111_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsByAge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minAge', models.PositiveSmallIntegerField()),
                ('maxAge', models.PositiveSmallIntegerField()),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PointsByFinancialSituation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_situation', models.CharField(choices=[('bad', 'Bad'), ('mid', 'Mid'), ('good', 'Good')], max_length=4)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PointsByParentWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_work', models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], max_length=3)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PointsBySpecialNeeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_needs', models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], max_length=3)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PointsByTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant', models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], max_length=3)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PointsByYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_year', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='scholarshiprequest',
            name='parent_work',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='scholarshiprequest',
            name='special_needs',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='scholarshiprequest',
            name='tenant',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='scholarshiprequest',
            name='volunteer',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], max_length=3),
        ),
    ]
