# Generated by Django 3.2.7 on 2023-01-12 18:05

from django.db import migrations

from app.reference_data.reference_data import create_reference_data


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0005_auto_20230111_2343'),
    ]

    operations = [
        migrations.RunPython(create_reference_data)
    ]
