# Generated by Django 3.2.7 on 2023-01-14 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_scholarshiprequest_id_alter_task_id_and_more'),
        ('app', '0006_auto_20230112_1805'),
    ]

    operations = [
    ]
