# Generated by Django 4.1.5 on 2023-01-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20230108_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='worker',
            name='gender',
            field=models.IntegerField(choices=[(0, 'male'), (1, 'female')]),
        ),
    ]
